export const BASE_URL = 'https://api.itaxeasy.com';

export const MOM_ITAX_URL = 'https://mom.itaxeasy.com/api';

export const token= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiSGFyc2giLCJsYXN0TmFtZSI6IlNpbmdoIiwiYWRkcmVzcyI6bnVsbCwiYWFkaGFhciI6IjEyMzQ1Njc4OTAxMSIsInBhbiI6IkFCQ0QxMjM0IiwiZW1haWwiOiJoYXJzaHNpbmdoLmpzQGdtYWlsLmNvbSIsInBob25lIjoiNzY1MjAzNTE1MiIsInVzZXJUeXBlIjoibm9ybWFsIiwidmVyaWZpZWQiOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDIzLTA4LTAyVDA0OjI1OjM0LjQwNloiLCJpYXQiOjE2OTA5NTA1MDIsImV4cCI6MTcyMjUwODEwMiwiaXNzIjoiaVRheEVhc3kifQ.f43Q1aqmkNIj_5S-7TUbJnMtDcLoL4p0jDw4nGlEBVQ"
